### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'animation\/effects\/arrow.atlas'

### ISSUE THREAD

**Issue by spinningD20** [richarddun/zipper#1]
Hi!  I'm really interested in seeing what someone else is doing with kivy and some of the tmx foundation Richard Jones used in his tutorials.  I pulled your master branch and it looks like the effects folder is missing.  

I'm also guessing you're using Windows?  As an aside, os.path could clean up your path references, and then be OS-agnostic.

Looking forward to seeing this in action!

**Comment by richarddun** [comment]
Hey, I appreciate your interest in the repo - thanks for stopping by!

Richard Jone's Kivy friendly tmx implementation is a stroke of genius, and has really made it a viable option for starters to Kivy and simple game dev like myself.

Thanks for the tip about os.path!  Though the issue was related to my git-fu, not actually adding the image directory to the repo in the first place :)

**Comment by spinningD20** [comment]
It's a fun start to a platformer, I'll keep checking in from time to time.  I'm really interested in finding others that are using or dabbling with kivy to make games.  

Regarding the effects folder, I figured it was just overlooked - I'm no expert in git either (yet!).

Kivent recently added Tiled support in their 2.2 dev branch, but entity-component design is much different than what I have experience in, so it's been more difficult for me to adapt to using.  The plus side is Kivent is extremely performant - whereas RJ's tmx code for kivy will run poorly after you get to a certain tile size / number of layers (for mobile platforms anyway, most computers will have a much higher map size ceiling).  

I'll be sure to follow your progress!
